user_column: user_id
session_column: user_session
item_column: product_id
timestamp_column: event_time
transaction_type_column: event_type
target_column: target_product_id
num_walks: 3
num_steps: 10
p: 1.
q: 1.
window_size: 10
num_negative_samples: 2
train_test_ratio: 0.6